Don't fail if facets inherit ERC165 function
Error was:

    Error: function "supportsInterface" will shadow "supportsInterface".
    Please update code to avoid conflict.